### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by breim** [chiligumdev/chili_player#1]
Hi
We need add gem rest-client in your gemfile project.

/home/henrique/.rvm/gems/ruby-2.3.3/gems/chili_player-0.1.0/lib/chili_player/videos.rb:3:in `require': cannot load such file -- rest-client (LoadError)
	from /home/henrique/.rvm/gems/ruby-2.3.3/gems/chili_player-0.1.0/lib/chili_player/videos.rb:3:in `<top (required)>'
	from /home/henrique/.rvm/gems/ruby-2.3.3/gems/chili_player-0.1.0/lib/chili_player/init.rb:3:in `require'
	from /home/henrique/.rvm/gems/ruby-2.3.3/gems/chili_player-0.1.0/lib/chili_player/init.rb:3:in `<top (required)>'
	from /home/henrique/.rvm/gems/ruby-2.3.3/gems/chili_player-0.1.0/lib/chili_player.rb:2:in `require'
	from /home/henrique/.rvm/gems/ruby-2.3.3/gems/chili_player-0.1.0/lib/chili_player.rb:2:in `<top (required)>'

**Comment by breim** [comment]
NameError: uninitialized constant ChiliGum

**Comment by MrCasimiro** [comment]
Hey.

I checked out the NameError and it was a typo in Readme, I fixed out here https://github.com/chiligumdev/chili_player/commit/e1502a2db6c8b623176398ad68891dfd25d54482

About the gem rest-client, it is already in gemfile, what is the issue specifically?

**Comment by breim** [comment]
ok

**Comment by MrCasimiro** [comment]
Fixed rest-client dependency here: https://github.com/chiligumdev/chili_player/commit/7478929cbbd89f9571ccc164971b43d02af3ad34

**Comment by breim** [comment]
Ok, fixed.
